### ISSUE TITLE
Need some help on test_simple please

### ISSUE THREAD

**Issue by lianzheng-research** [wencheng256/BRNet#5]
Thanks for your great work. Now I want to test the code and run test_simple, but I got the following error.
-> Loading model from  models/mono+stereo_640x192
   Loading pretrained encoder
Traceback (most recent call last):
  File "test_simple.py", line 171, in <module>
    test_simple(args)
  File "test_simple.py", line 88, in test_simple
    encoder.load_state_dict(filtered_dict_enc)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetEncoder:
        Missing key(s) in state_dict: "mha_scale", "global_encoder.layer1.0.conv1.weight", "global_encoder.layer1.0.bn1.weight", "global_encoder.layer1.0.bn1.bias", "global_encoder.layer1.0.bn1.running_mean", "global_encoder.layer1.0.bn1.running_var", "global_encoder.layer1.0.conv2.weight", "global_encoder.layer1.0.bn2.weight", "global_encoder.layer1.0.bn2.bias", "global_encoder.layer1.0.bn2.running_mean", "global_encoder.layer1.0.bn2.running_var", "global_encoder.layer1.1.conv1.weight", "global_encoder.layer1.1.bn1.weight", "global_encoder.layer1.1.bn1.bias", "global_encoder.layer1.1.bn1.running_mean", "global_encoder.layer1.1.bn1.running_var", "global_encoder.layer1.1.conv2.weight", "global_encoder.layer1.1.bn2.weight", "global_encoder.layer1.1.bn2.bias", "global_encoder.layer1.1.bn2.running_mean", "global_encoder.layer1.1.bn2.running_var", "global_encoder.layer2.0.conv1.weight", "global_encoder.layer2.0.bn1.weight", "global_encoder.layer2.0.bn1.bias", "global_encoder.layer2.0.bn1.running_mean", "global_encoder.layer2.0.bn1.running_var", "global_encoder.layer2.0.conv2.weight", "global_encoder.layer2.0.bn2.weight", "global_encoder.layer2.0.bn2.bias", "global_encoder.layer2.0.bn2.running_mean", "global_encoder.layer2.0.bn2.running_var", "global_encoder.layer2.1.conv1.weight", "global_encoder.layer2.1.bn1.weight", "global_encoder.layer2.1.bn1.bias", "global_encoder.layer2.1.bn1.running_mean", "global_encoder.layer2.1.bn1.running_var", "global_encoder.layer2.1.conv2.weight", "global_encoder.layer2.1.bn2.weight", "global_encoder.layer2.1.bn2.bias", "global_encoder.layer2.1.bn2.running_mean", "global_encoder.layer2.1.bn2.running_var", "mha_weight.0.weight", "mha_weight.0.bias", "multihead_attn.in_proj_weight", "multihead_attn.in_proj_bias", "multihead_attn.out_proj.weight", "multihead_attn.out_proj.bias", "pos_edb.row_embed.weight", "pos_edb.col_embed.weight".

What should I do to make it work? Thanks again!

**Comment by wencheng256** [comment]
It seems that you load the wrong pth file. Please check if the file you load in the test phase is trained by this repo.
